config/routes.rb
Rails.application.routes.draw do
  root 'invoices#index'
  resources :invoices do
    member do
      post 'sender_invoice'
    end
  end

end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  phone      :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#
# Indexes
#
#  index_customers_on_email  (email) UNIQUE
#

class Customer < ActiveRecord::Base
  has_many :invoices, dependent: :destroy
end

app/models/invoice.rb
# == Schema Information
#
# Table name: invoices
#
#  id          :integer          not null, primary key
#  number      :integer
#  issue_date  :date
#  due_date    :date
#  customer_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#
# Indexes
#
#  index_invoices_on_customer_id  (customer_id)
#  index_invoices_on_number       (number) UNIQUE
#

class Invoice < ActiveRecord::Base
  has_many :invoice_items, dependent: :destroy
  belongs_to :customer

  before_create :create_unique_identifier

  validates_presence_of :customer_id

  accepts_nested_attributes_for :invoice_items, allow_destroy: true

  def total
    self.invoice_items.each.inject(0) { |sum, i| sum += i.amount }
  end

  def subtotal
    self.invoice_items.each.inject(0) { |sum, i| sum += i.unitary_cost }
  end

  def invoice_path
    "#{Rails.root}/pdfs/invoice-#{self.number}.pdf"
  end

private

  def create_unique_identifier
    begin
      self[:number] = SecureRandom.random_number(1_000_000)
    end while self.class.exists?(number: number)
  end
end

app/models/invoice_item.rb
# == Schema Information
#
# Table name: invoice_items
#
#  id           :integer          not null, primary key
#  quantity     :integer          default(1)
#  description  :string(255)
#  unitary_cost :decimal(15, 3)
#  invoice_id   :integer
#  created_at   :datetime
#  updated_at   :datetime
#
# Indexes
#
#  index_invoice_items_on_invoice_id  (invoice_id)
#

class InvoiceItem < ActiveRecord::Base
  belongs_to :invoice

  def amount
    self[:unitary_cost] * self[:quantity]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
    @invoices = Invoice.all
  end

  def show
    @invoice = @invoice = Invoice.find(params[:id])

    respond_to do |format|
      format.html
      format.pdf do
        pdf = InvoicePdf.new(@invoice)
        send_data pdf.render, filename: "invoice_#{@invoice.number}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end

  def new
    @invoice = Invoice.new
    @invoice.invoice_items.build
  end

  def edit
    @invoice = Invoice.find(params[:id])
  end

  def update
    @invoice = Invoice.find(params[:id])

    if @invoice.update(invoice_params)
      flash[:notice] = "Invoice has been updated."
      redirect_to @invoice
    else
      flash[:alert] = "Invoice has not been updated."
      render action: "edit"
    end
  end

  def create
    @invoice = Invoice.new(invoice_params)

    if @invoice.save
      flash[:notice] = "Invoice has been created."
      redirect_to @invoice
    else
      flash[:alert] = "Invoice has not been created."
      render "new"
    end
  end

  def sender_invoice
    @invoice = Invoice.find(params[:id])

    InvoicesMailer.send_invoice({
      email:        @invoice.customer.email,
      invoice_path: @invoice.invoice_path,
      number:       @invoice.number,
      due_date:     @invoice.due_date
      }).deliver

    redirect_to root_url, notice: "Delivered newsletter."
  end

  private

  def invoice_params
    params.require(:invoice).permit(:customer_id, :due_date, :issue_date, invoice_items_attributes: [ :id, :description, :quantity, :unitary_cost, :_destroy ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>

  <% if @invoice.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>
      <ul>
      <% @invoice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<fieldset>
  <legend>Invoice Informations</legend>
  <div class="field">
    <%= f.label :customer %><br />
    <%= f.collection_select(:customer_id, Customer.all, :id, :name, { prompt: true }) %>
  </div>

  <div class="field">
    <%= f.label :issue_date %><br />
    <%= f.date_field :issue_date %>
  </div>

  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.date_field :due_date %>
  </div>
</fieldset>



  <%= f.fields_for :invoice_items do |builder| %>
    <%= render 'invoice_item_fields', f: builder %>
  <% end %>


<%= link_to_add_fields "Add Item", f, :invoice_items %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/_invoice_item_fields.html.erb
<fieldset>
  <legend>Invoice Item</legend>
  <%= f.label :description %><br />
  <%= f.text_field :description %><br />

  <%= f.label :quantity %><br />
  <%= f.number_field :quantity %><br />

  <%= f.label :unitary_cost %><br />
  <%= f.text_field :unitary_cost %><br />

  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove Item" %>
</fieldset>

app/views/invoices/edit.html.erb
<h1>Edit Invoice</h1>

<%= render "form" %>

app/views/invoices/index.html.erb
<h1>Invoices</h1>

<table>
 <thead>
  <tr>
   <th>ID</th>
   <th>Invoice Customer</th>
   <th>Actions</th>
  </tr>
</thead>
<tbody>
  <% @invoices.each do |invoice| %>
    <tr>
      <td><%= invoice.number %></td>
      <td><%= invoice.customer.name %></td>
      <td>
        <%= link_to "Enviar", sender_invoice_invoice_path(invoice), method: :post %> |
        <%= link_to "Visualizar", invoice_path(invoice, format: "pdf") %> |
        <%= link_to "Editar", edit_invoice_path(invoice) %>
      </td>
    </tr>
  <% end %>
</tbody>
</table>

<p><%= link_to "New Invoice", new_invoice_path %></p>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finance</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>